project:
  type: website

website:
  title: "Photonics Notes"
  description: "Notes, tutorials, and perspectives on modern photonics."
  site-url: https://shnam2222.github.io/photonics_blog/

  navbar:
    left:
      - text: Foundations
        href: foundations/index.qmd

      - text: Resonances
        href: resonances/index.qmd

      - text: Metasurfaces
        href: metasurfaces/index.qmd

      - text: Computational
        href: computational/index.qmd

      - text: Research
        href: research/index.qmd

    right:
      - text: Author
        href: author.qmd

      - icon: github
        href: https://github.com/shnam2222

  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap